spring.application.name=demoTestIntegration

# Configuration de la base PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nom_de_ta_base
spring.datasource.username=ton_utilisateur
spring.datasource.password=ton_mot_de_passe
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true